media:
  input: src/assets/images
  output: src/assets/images
content:
  - name: posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string

      - name: description
        label: Description

      - name: date
        label: Published Datetime
        type: date
        options: 
          format: "yyyy-MM-dd"

      - name: body
        label: Body
        type: rich-text
    view:
      fields: [title, description, date]
    filename: "{primary}.md"